### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by amdecker** [MIT-PSFC/disruption-py#292]
## New tools
- [x] [tqdm](https://tqdm.github.io/) because it makes progress bars very easy to implement
    - Both standard logging and loguru can be made compatible with it by adding a custom handler
    - TQDM will be easy to integrate after changes in https://github.com/MIT-PSFC/disruption-py/pull/271
- [x] [loguru](https://loguru.readthedocs.io/en/stable/overview.html)  
    - Benefits over standard logging:
        - Easy formatting of strings, colors
        - Works with multiprocessing with [`enqueue` parameter](https://loguru.readthedocs.io/en/stable/overview.html#asynchronous-thread-safe-multiprocess-safe). The standard logger [does not support](https://docs.python.org/3/howto/logging-cookbook.html#logging-to-a-single-file-from-multiple-processes) multiprocessing
        - We could use their built-in exception [catcher/logger decorator](https://loguru.readthedocs.io/en/stable/overview.html#exceptions-catching-within-threads-or-main)

### Basic Examples log + tqdm
Standard logging
```python
import logging
import time

from tqdm.auto import tqdm


class TqdmLoggingHandler(logging.Handler):
    def emit(self, record):
            msg = self.format(record)
            tqdm.write(msg)
            
            
logger = logging.getLogger("example")
logger.setLevel(logging.INFO)
tqdm_handler = TqdmLoggingHandler()
formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
tqdm_handler.setFormatter(formatter)

logger.addHandler(tqdm_handler)

for i in tqdm(range(10)):
    time.sleep(0.5)
    logger.info(f"Completed iteration {i + 1}")
```

Loguru
```python
import time

from loguru import logger
from tqdm.auto import tqdm

class TqdmLoggingHandler:
    def write(self, message):
        tqdm.write(message, end='')

# Remove the default handler
logger.remove()  

# Add tqdm handler
logger.add(TqdmLoggingHandler(), format="<red>{time}</red> <level>{message}</level>", colorize=True)

x = 0
for i in tqdm(range(10)):
    time.sleep(0.5)
    logger.opt(colors=True).debug("{loop_idx} <green>this is green</> <red>this is red</>", loop_idx=i)
    logger.debug("debug color")
    logger.warning("this is warning color")
```

## Proposed changes to logging content
- [x] Add information about Python version to the beginning of a log file
    - E.g. log `os.getenv("VIRTUAL_ENV")` which outputs ~`'/home/<USER>/.cache/pypoetry/virtualenvs/disruption-py-PxLlHk9W-py3.10'`
- [x] To support multiple verbosity levels e.g. verbose/not verbose we could add a level after INFO, but before warning (loguru already does this and calls it the ["success" level](https://loguru.readthedocs.io/en/stable/overview.html#exceptions-catching-within-threads-or-main). This level would output statistics at the end like "9/10 shots grabbed data successfully". 
    - Being able to write summaries like "9/10 shots grabbed data successfully" would require either inspecting the data returned from the physics methods to look for all `nan` in a column or by catching exceptions higher up  (maybe runner.py) than in the physics methods themselves
        - We might need to change the DIII-D physics methods to return `nan` for all quantities when there is an exception just like we do with CMod physics methods rather than the single quantity that had an error (current behavior)
- [x] Reformat the log messages. 
    - Remove logger name "disruption_py" because we only have one logger
    - Instead of writing "shot {shotid}" we can write "#{shotid}" or just "{shotid}"

##

**Comment by gtrevisan** [comment]
implemented with:
- #319
