### ISSUE TITLE
Some parameters fail for set of C-Mod shots from 1998

### ISSUE THREAD

**Issue by andrew-maris** [MIT-PSFC/disruption-py#30]
Some shots from 1998 ([cmod_hdl_ids.txt](https://github.com/MIT-PSFC/disruption-py/files/11910411/cmod_hdl_ids.txt)) are failing to get all EFIT parameters, density parameters, and power parameters.

My suspicion is this all caused by some efit parameters not existing. Below are the confirmed values that are missing and suggested "back up" ways of getting the values based on parameters that do exist

- aminor -->  \efit_aeqdsk:aout
- beta_n --> 1/( 1/ \efit_aeqdsk:betat + 1/ \efit_aeqdsk:betap) ([see here](http://wiki.fusenet.eu/fusionwiki/index.php/Beta))
- li --> \efit_aeqdsk:ali
- q0 -->  \efit_aeqdsk:qqmagx
- qstar -->  \efit_aeqdsk:qsta
- q95 -->  \efit_aeqdsk:qsib (not totally sure on this one)
- v_loop --> deriv(\ANALYSIS::EFIT_SSIMAG)*$2pi  (not totally sure on this one)
- wmhd--> \efit_aeqdsk:wplasm (not totally sure on this one)

How would we go about changing CModShot so that it will use these backups if the original efit values are missing?

I think some of the power efit names are also missing, but haven't tracked those down yet

**Comment by gtrevisan** [comment]
this should have been closed by:
- #332 

@andrew-maris please LMK otherwise! thank you.
