### ISSUE TITLE
OSSFE 2025

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [MIT-PSFC/disruption-py#331]
Congrats on open-sourcing this!

Would you consider submitting an abstract at the Open Source Software for Fusion Energy conference?

See https://ossfe.github.io/

@allen-adastra @gtrevisan

**Comment by gtrevisan** [comment]
thanks, we'll take a look!

**Comment by allen-adastra** [comment]
I'm not a main developer of disruption-py; def all Greg and crew 🙂

I'd be happy to submit an abstract on POPSIM; assuming you are okay with me presenting software that is "supposed to be open source eventually".

Cheers,
Allen
________________________________

**Comment by RemDelaporteMathurin** [comment]
> assuming you are okay with me presenting software that is "supposed to be open source eventually".

I think the committee would prefer avoiding this as often we heard that and things never got released ;-) Better if there's already an Open Source licence
